default: &default
  adapter: postgresql
  encoding: unicode
  host: pg_db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: social_media_api_development

test:
  <<: *default
  database: social_media_api_test

production:
  <<: *default
  database: social_media_api_production
